### ISSUE TITLE
support idempotency annotations

### ISSUE THREAD

**Issue by ccmtaylor** [soundcloud/twinagle#9]
use https://github.com/protocolbuffers/protobuf/blob/3a3956e8a258784461270961c6577341356bce52/src/google/protobuf/descriptor.proto#L678 to determine if failures should be retryable

**Comment by oberkowitz** [comment]
I think that this is likely not worth pursuing at this time. It isn't part of the Twirp protocol or implementation, and it's not something that exists in GRPC either. There's a lot of complexity once you start to dive in, and I think that we can live without it. WDYT? @stevesoundcloud @ccmtaylor @dziemba
